# Site settings
title: "Land Registry Digital Service" # replace this with your own
author: "Land Registry Digital Service" # replace this with your own
email:
description: "Land Registry Digital Service"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.landregistryconcept.co.uk/"
theme: bootstrap



# Build settings
markdown: kramdown
permalink: pretty
exclude: [vendor]
