# Site settings
title: "Land Registry open source code"
description: "Open source code and accompanying documentation for the Land Registry digital service"
baseurl: ""
url: "localhost:4000"

# Build settings
markdown: kramdown
permalink: pretty
