# Site settings
title: "Land Registry Digital Service"
author: "Land Registry Digital Service"
email:
description: "Land Registry Digital Service"
baseurl: ""
url: "http://www.landregistryconcept.co.uk/"
theme: bootstrap



# Build settings
markdown: kramdown
permalink: pretty
exclude: [vendor]
